[package]
name = "apalis-sqlx-bug"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { path = "crates/db" }
worker = { path = "crates/worker" }

[workspace]
resolver = "3"
members = ["crates/*"]
